# 接続先の定義
upstream original_app {
    server web:3000;
}

server {
    listen 80;
    server_name flaag.net;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://original_app;
    }
}